/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ユーザーのルート一覧を取得する */
        get: {
            parameters: {
                query?: {
                    /** @description Keyword to search in route names */
                    keyword?: string;
                    /** @description Minimum distance filter */
                    min_distance?: string;
                    /** @description Maximum distance filter */
                    max_distance?: string;
                    /** @description Minimum elevation gain filter */
                    min_elevation?: string;
                    /** @description Maximum elevation gain filter */
                    max_elevation?: string;
                    /** @description Visibility filter */
                    visibility?: string;
                    /** @description Author filter */
                    author?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["route.RouteListResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** ルートを作成する */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Create Route Request */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["route.CreateRouteRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["route.RouteResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{route_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ルートを取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Route ID */
                    route_id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["route.RouteResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
            };
        };
        /** ルートを更新する */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Route ID */
                    route_id: string;
                };
                cookie?: never;
            };
            /** @description Update Route Request */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["route.UpdateRouteRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** ルートを削除する */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Route ID */
                    route_id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ユーザーを作成する */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Create User Request */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["user.CreateUserRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["user.UserResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ユーザーを取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["user.UserResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "response.ErrorResponse": {
            /** @example 400 */
            code?: number;
            /** @example Bad Request */
            msg?: string;
        };
        "route.CoursePointRequest": {
            bearing_after?: number;
            bearing_before?: number;
            cum_dist_m?: number;
            duration?: number;
            instruction?: string;
            location: string;
            maneuver_type?: string;
            modifier?: string;
            road_name?: string;
            seg_dist_m?: number;
        };
        "route.CoursePointResponse": {
            bearing_after?: number;
            bearing_before?: number;
            cum_dist_m?: number;
            duration?: number;
            id?: string;
            instruction?: string;
            location?: string;
            maneuver_type?: string;
            modifier?: string;
            road_name?: string;
            seg_dist_m?: number;
            step_order?: number;
        };
        "route.CreateRouteRequest": {
            course_points?: components["schemas"]["route.CoursePointRequest"][];
            description?: string;
            distance: number;
            duration: number;
            elevation_gain?: number;
            elevation_loss?: number;
            first_point: string;
            highlighted_photo_id?: number;
            last_point: string;
            name: string;
            path_geom: string;
            visibility: number;
            waypoints?: components["schemas"]["route.WaypointRequest"][];
        };
        "route.RouteListResponse": {
            routes?: components["schemas"]["route.RouteResponseModel"][];
        };
        "route.RouteResponse": {
            route?: components["schemas"]["route.RouteResponseModel"];
        };
        "route.RouteResponseModel": {
            bbox?: string;
            course_points?: components["schemas"]["route.CoursePointResponse"][];
            created_at?: string;
            description?: string;
            distance?: number;
            duration?: number;
            elevation_gain?: number;
            elevation_loss?: number;
            first_point?: string;
            highlighted_photo_id?: number;
            id?: string;
            last_point?: string;
            name?: string;
            path_geom?: string;
            updated_at?: string;
            user_id?: string;
            user_name?: string;
            visibility?: number;
            waypoints?: components["schemas"]["route.WaypointResponse"][];
        };
        "route.UpdateRouteRequest": {
            course_points?: components["schemas"]["route.CoursePointRequest"][];
            description?: string;
            distance: number;
            duration: number;
            elevation_gain?: number;
            elevation_loss?: number;
            first_point: string;
            highlighted_photo_id?: number;
            last_point: string;
            name: string;
            path_geom: string;
            visibility: number;
            waypoints?: components["schemas"]["route.WaypointRequest"][];
        };
        "route.WaypointRequest": {
            location: string;
        };
        "route.WaypointResponse": {
            id?: string;
            location?: string;
        };
        "user.CreateUserRequest": {
            email?: string;
            first_name?: string;
            kratos_id: string;
            last_name?: string;
            name: string;
        };
        "user.UserResponse": {
            user?: components["schemas"]["user.UserResponseModel"];
        };
        "user.UserResponseModel": {
            administrative_area?: string;
            country_code?: string;
            description?: string;
            email?: string;
            first_name?: string;
            geom?: string;
            has_set_location?: boolean;
            highlighted_photo_id?: number;
            id?: string;
            last_name?: string;
            locale?: string;
            locality?: string;
            name?: string;
            postal_code?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
